name: CI/CD

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      GIT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v2

      - name: Stylesheet check
        run: echo 'stylesheet check'

      - name: Build image
        run: echo 'building'

      - name: Run tests
        run: echo 'running tests'

      - name: SonarCloud Report coverage
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy_dev:
    if: github.ref == 'refs/heads/dev'
    needs: integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  deploy_main:
    if: github.ref == 'refs/heads/main'
    needs: integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
