name: Pre-release

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout branch "main"
        uses: actions/checkout@v2
        with:
          ref: "main"
      - name: Retrieve SonarCloud Metrics
        run: curl "https://sonarcloud.io/api/measures/component_tree?component=fga-eps-mds_2021.1-PCTs-ML-Training&metricKeys=files,functions,complexity,comment_lines_density,duplicated_lines_density,coverage,ncloc,security_rating,tests,test_success_density,test_execution_time,reliability_rating&ps=500" -o fga-eps-mds_2021.1-PCTs-ML-Training-${{ steps.date.outputs.date }}.json
      - name: Release snapshot
        id: release-snapshot
        uses: marvinpinto/action-automatic-releases@v1.1.1
        with:
          title: "pre-release"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          files: |
            fga-eps-mds_2021.1-PCTs-ML-Training-${{ steps.date.outputs.date }}.json
